version: '3'
services:
  web:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  db:
    image: firebase/firebase-tools
    environment:
      FIREBASE_TOKEN: <clientdb-e7462-firebase-adminsdk-iqoz7-45cb0788ed.json>
    volumes:
      - ./firebase:/app/firebase
    command: "firebase serve --only hosting"

# version: '3'
# services:
#   web:
#     image: php:apache
#     ports:
#       - "80:80"
#     volumes:
#       - ./:/var/www/html/
   